# Generated by Django 2.1.4 on 2021-02-16 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField(blank=True, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('occupation_training', models.TextField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialAdvisors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField(null=True)),
                ('register', models.TextField(null=True)),
                ('company', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FixedIncomeSecurities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('tx', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImmovableProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('rented', models.NullBooleanField()),
                ('funded', models.NullBooleanField()),
                ('insurance_value', models.FloatField(blank=True, null=True)),
                ('insurance_company', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insurances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('monthly_fee', models.NullBooleanField()),
                ('coverage', models.FloatField(blank=True, null=True)),
                ('company', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentPortfolios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('tx', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorExperiences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalPrivateSecurities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.TextField(blank=True, null=True)),
                ('enterprise', models.TextField(blank=True, null=True)),
                ('cooperative', models.TextField(blank=True, null=True)),
                ('survival', models.TextField(blank=True, null=True)),
                ('table', models.TextField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fullname', models.TextField(blank=True, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('preferred_contact', models.TextField(blank=True, null=True)),
                ('occupation', models.TextField(blank=True, null=True)),
                ('role', models.TextField(blank=True, null=True)),
                ('company_name', models.TextField(blank=True, null=True)),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('business_kind', models.TextField(blank=True, null=True)),
                ('business_field', models.TextField(blank=True, null=True)),
                ('company_has_private_insurance', models.NullBooleanField()),
                ('social_security_value', models.FloatField(blank=True, null=True)),
                ('private_security_your_value', models.FloatField(blank=True, null=True)),
                ('private_security_company_value', models.FloatField(blank=True, null=True)),
                ('private_security_current_balance', models.FloatField(blank=True, null=True)),
                ('income_tax_declaration_type', models.TextField(blank=True, null=True)),
                ('monthly_expenses', models.FloatField(blank=True, null=True)),
                ('costs_with_dependents', models.FloatField(blank=True, null=True)),
                ('how_much_you_save', models.FloatField(blank=True, null=True)),
                ('debt_loans', models.FloatField(blank=True, null=True)),
                ('partner_in_company', models.FloatField(blank=True, null=True)),
                ('health', models.TextField(blank=True, null=True)),
                ('plans_and_projects', models.TextField(blank=True, null=True)),
                ('current_investment_process', models.TextField(blank=True, null=True)),
                ('follow_economic_news', models.NullBooleanField()),
                ('accepts_info_about_courses', models.NullBooleanField()),
                ('have_financial_concerns', models.TextField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('portfolio_income', models.FloatField(blank=True, null=True)),
                ('accept_financial_advisor_contact', models.NullBooleanField()),
                ('financial_advisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='functions.FinancialAdvisors')),
            ],
        ),
        migrations.AddField(
            model_name='phones',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='functions.Profile'),
        ),
        migrations.AddField(
            model_name='personalprivatesecurities',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='functions.Profile'),
        ),
        migrations.AddField(
            model_name='investorexperiences',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='functions.Profile'),
        ),
        migrations.AddField(
            model_name='investmentportfolios',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='functions.Profile'),
        ),
        migrations.AddField(
            model_name='insurances',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='functions.Profile'),
        ),
        migrations.AddField(
            model_name='immovableproperties',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='functions.Profile'),
        ),
        migrations.AddField(
            model_name='fixedincomesecurities',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='functions.Profile'),
        ),
        migrations.AddField(
            model_name='children',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='functions.Profile'),
        ),
    ]
