# Generated by Django 2.1.4 on 2021-01-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthdate',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fullname',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_contact',
            field=models.TextField(blank=True),
        ),
    ]
