# Generated by Django 2.2 on 2021-03-04 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialadvisors',
            name='cpf',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialadvisors',
            name='company',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialadvisors',
            name='fullname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialadvisors',
            name='register',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AdvisorsLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('link', models.TextField()),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.FinancialAdvisors')),
            ],
        ),
    ]
