# Generated by Django 2.1.4 on 2021-02-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='maritalHowManyYears',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='maritalStatus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='parentsAreThemSupportedByYou',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='profile',
            name='parentsHowMuchYouSuportThem',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='parentsIsThereAPossibilityOfInheritance',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='profile',
            name='parentsOfWhom',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='parentsWhatIsTheEstimatedValue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='spouseName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='spouseOccupation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
