# Generated by Django 2.1.4 on 2021-02-12 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmovableProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('rented', models.NullBooleanField()),
                ('funded', models.NullBooleanField()),
                ('insurance_value', models.FloatField(blank=True, null=True)),
                ('insurance_company', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insurances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('monthly_fee', models.NullBooleanField()),
                ('coverage', models.FloatField(blank=True, null=True)),
                ('company', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorExperiences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='token',
            new_name='cpf',
        ),
        migrations.AddField(
            model_name='profile',
            name='accepts_info_about_courses',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='profile',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='business_field',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='business_kind',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_has_private_insurance',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='costs_with_dependents',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_investment_process',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='debt_loans',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='follow_economic_news',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='profile',
            name='fullname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='have_financial_concerns',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='health',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='how_much_you_save',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='income_tax_declaration_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='monthly_expenses',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='partner_in_company',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='plans_and_projects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio_income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_contact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='private_security_company_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='private_security_current_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='private_security_your_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_security_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phones',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.Profile'),
        ),
        migrations.AddField(
            model_name='investorexperiences',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.Profile'),
        ),
        migrations.AddField(
            model_name='insurances',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.Profile'),
        ),
        migrations.AddField(
            model_name='immovableproperties',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.Profile'),
        ),
    ]
