# Generated by Django 2.1.4 on 2021-01-22 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0002_auto_20210115_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='phones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='functions.Phone'),
        ),
    ]
