# Generated by Django 2.1.4 on 2021-02-11 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0002_auto_20210211_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('monthly_fee', models.NullBooleanField()),
                ('coverage', models.FloatField(blank=True, null=True)),
                ('company', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.Profile')),
            ],
        ),
    ]
