# Generated by Django 2.1.4 on 2021-01-19 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0002_auto_20210115_0405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='token',
            new_name='cpf',
        ),
    ]
