# Generated by Django 2.1.4 on 2021-01-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0002_auto_20210108_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='setProfile',
        ),
    ]
