# Generated by Django 2.1.4 on 2021-02-12 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0003_investmentportfolios'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalPrivateSecurities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.TextField(blank=True, null=True)),
                ('enterprise', models.TextField(blank=True, null=True)),
                ('cooperative', models.TextField(blank=True, null=True)),
                ('survival', models.TextField(blank=True, null=True)),
                ('table', models.TextField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.Profile')),
            ],
        ),
    ]
