# Generated by Django 2.2 on 2021-03-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0003_profile_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentportfolios',
            name='tx_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
