# Generated by Django 2.1.4 on 2021-01-08 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0003_auto_20210108_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='token',
        ),
    ]
