# Generated by Django 2.1.4 on 2021-01-22 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0003_auto_20210119_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phones',
        ),
        migrations.AddField(
            model_name='phones',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.Profile'),
        ),
    ]
