# Generated by Django 2.1.4 on 2021-01-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0004_remove_model_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='token',
            field=models.TextField(blank=True),
        ),
    ]
