# Generated by Django 2.2 on 2021-04-10 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0004_investmentportfolios_tx_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAdvisors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.FinancialAdvisors')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.Profile')),
            ],
        ),
        migrations.AddIndex(
            model_name='profileadvisors',
            index=models.Index(fields=['profile'], name='profile_idx'),
        ),
        migrations.AddIndex(
            model_name='profileadvisors',
            index=models.Index(fields=['advisor'], name='advisor_idx'),
        ),
        migrations.AddConstraint(
            model_name='profileadvisors',
            constraint=models.UniqueConstraint(fields=('profile', 'advisor'), name='profile_advisor_uk'),
        ),
    ]
