# Generated by Django 2.1.4 on 2021-01-08 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0005_model_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Modelo',
        ),
    ]
