# Generated by Django 2.1.4 on 2021-02-07 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0005_auto_20210202_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmovableProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('rented', models.NullBooleanField()),
                ('funded', models.NullBooleanField()),
                ('insurance_value', models.TextField(blank=True, null=True)),
                ('insurance_company', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='accepts_info_about_courses',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='profile',
            name='addicional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='costs_with_dependents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_investment_process',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='debt_loans',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='follow_economic_news',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='profile',
            name='have_financial_concerns',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='health',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='how_much_you_save',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='monthly_expenses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='partner_in_company',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='plans_and_projects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='immovableproperties',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.Profile'),
        ),
    ]
