# Generated by Django 2.2 on 2021-07-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0006_auto_20210410_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileadvisors',
            name='main_advisor',
            field=models.NullBooleanField(),
        ),
    ]
