# Generated by Django 2.1.4 on 2021-01-09 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0006_auto_20210108_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='token',
        ),
    ]
