# Generated by Django 2.1.4 on 2021-01-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0007_remove_modelo_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='token',
            field=models.TextField(blank=True),
        ),
    ]
