# Generated by Django 2.1.4 on 2021-01-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0008_modelo_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelo',
            old_name='token',
            new_name='dado',
        ),
    ]
