# Generated by Django 2.2 on 2021-07-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0008_auto_20210705_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileadvisors',
            name='main_advisor',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
