# Generated by Django 2.1.4 on 2021-01-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0009_auto_20210109_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelo',
            old_name='dado',
            new_name='token',
        ),
    ]
