# Generated by Django 2.2 on 2021-07-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0009_auto_20210707_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialadvisors',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
