# Generated by Django 2.2 on 2021-07-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0010_auto_20210722_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialadvisors',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
