# Generated by Django 2.2 on 2021-08-12 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0010_profile_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Targets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible_cpf', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('present_value', models.FloatField(blank=True, null=True)),
                ('monthly_investment', models.FloatField(blank=True, null=True)),
                ('lower_variation', models.FloatField(blank=True, null=True)),
                ('upper_variation', models.FloatField(blank=True, null=True)),
                ('year_to_start_withdraw', models.IntegerField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.Profile')),
            ],
        ),
    ]
