# Generated by Django 2.2 on 2021-08-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0011_targets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
