# Generated by Django 2.2 on 2021-08-19 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0014_auto_20210818_0514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suitability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('interest', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='targets',
            name='investmentType',
        ),
        migrations.DeleteModel(
            name='investmentType',
        ),
        migrations.AddField(
            model_name='targets',
            name='suitability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='functions.Suitability'),
        ),
    ]
